### Imports

In [24]:
import pandas as pd
import gspread
from gspread_dataframe import set_with_dataframe
from list_scraper_daily import main, get_data
from datetime import datetime, timedelta

### Functions

In [25]:
def count_filled_rows(worksheet):
    # Get the values in the worksheet
    values = worksheet.get_all_values()
    
    # Check if the sheet is empty
    if not values:
        return 0  # Return 0 if the sheet is empty
    
    # Count the number of non-empty rows
    num_rows_filled = sum(1 for row in values if any(row))
    
    return num_rows_filled

### Get the data from WG-Gesucht

In [26]:
# Get data to append
YESTERDAY = (datetime.now().date() - timedelta(days=1)).strftime('%d.%m.%Y')
append_df = get_data(date=YESTERDAY)

[14:45:00][0] 23.03.2024 not reached yet.
[14:45:05][1] 23.03.2024 not reached yet.
[14:45:10][2] 23.03.2024 not reached yet.
[14:45:16][3] 23.03.2024 not reached yet.
[14:45:21][4] 23.03.2024 not reached yet.
[14:45:28][5] 23.03.2024 not reached yet.
[14:45:33][6] 23.03.2024 not reached yet.
[14:45:37] An exception occurred: 'NoneType' object has no attribute 'tbody'
https://www.wg-gesucht.de/cuba.html?page=/wg-zimmer-in-Berlin.8.0.0.7.html
Retrying in 116.72636008983585 seconds...
[14:47:35] An exception occurred: 'NoneType' object has no attribute 'tbody'
https://www.wg-gesucht.de/cuba.html?page=/wg-zimmer-in-Berlin.8.0.0.7.html
Retrying in 120.52817769290064 seconds...
[14:49:40] An exception occurred: 'NoneType' object has no attribute 'tbody'
https://www.wg-gesucht.de/cuba.html?page=/wg-zimmer-in-Berlin.8.0.0.7.html
14:49:40][7] Could not scrape: https://www.wg-gesucht.de/wg-zimmer-in-Berlin.8.0.0.7.html
[14:49:44] An exception occurred: 'NoneType' object has no attribute 'tbody'
https://www.wg-gesucht.de/cuba.html?page=/wg-zimmer-in-Berlin.8.0.0.8.html
Retrying in 103.38422719831885 seconds...

In [ ]:
append_df.empty

False

In [ ]:
append_df

,wg_id,href,size_and_genders,entry_date,price,sqr_m,city_part,available_from,available_to
0,10922437,wg-zimmer-in-Berlin-Kreuzberg.10922437.html,"4er WG (0w,3m,0d)",23.03.2024,890,30,Berlin Kreuzberg,16.04.2024,26.05.2024
1,10921751,wg-zimmer-in-Berlin-Steglitz-Zehlendorf.109217...,"3er WG (2w,0m,0d)",23.03.2024,500,15,Berlin Steglitz-Zehlendorf,01.04.2024,
2,8725181,wg-zimmer-in-Berlin-Samariterstrae.8725181.html,"3er WG (1w,1m,0d)",23.03.2024,600,19,Berlin Samariterstrae,01.04.2024,31.05.2024
3,10906997,wg-zimmer-in-Berlin-Berlin.10906997.html,"5er WG (2w,2m,0d)",23.03.2024,600,18,Berlin Berlin,01.06.2024,31.08.2024
4,9801883,wg-zimmer-in-Berlin-Pankow.9801883.html,"4er WG (2w,1m,0d)",23.03.2024,999,30,Berlin Pankow,01.04.2024,
5,10787489,wg-zimmer-in-Berlin.10787489.html,"3er WG (1w,1m,0d)",23.03.2024,710,15,Berlin,01.04.2024,
6,9771319,wg-zimmer-in-Berlin-Schoeneberg.9771319.html,"3er WG (2w,0m,0d)",23.03.2024,999,30,Berlin Schöneberg,23.03.2024,
7,9721483,wg-zimmer-in-Berlin-Treptow.9721483.html,"2er WG (0w,1m,0d)",23.03.2024,750,26,Berlin Treptow,01.04.2024,01.07.2024
8,10223580,wg-zimmer-in-Berlin-Schoeneberg.10223580.html,"2er WG (0w,1m,0d)",23.03.2024,880,33,Berlin Schöneberg,25.03.2024,
9,10922273,wg-zimmer-in-Berlin-Neukoelln.10922273.html,"2er WG (0w,1m,0d)",23.03.2024,440,10,Berlin Neukölln,01.04.2024,30.03.2025
10,8820510,wg-zimmer-in-Berlin-Neukoelln.8820510.html,"2er WG (1w,0m,0d)",23.03.2024,299,26,Berlin Neukölln,30.03.2024,19.04.2024
11,5011712,wg-zimmer-in-Berlin-Wedding.5011712.html,"3er WG (0w,1m,0d)",23.03.2024,400,16,Berlin Wedding,23.03.2024,30.04.2024
12,10899601,wg-zimmer-in-Berlin-Schoeneberg.10899601.html,"2er WG (0w,1m,0d)",23.03.2024,890,17,Berlin Schöneberg,23.03.2024,
13,10614386,wg-zimmer-in-Berlin-Charlottenburg.10614386.html,"3er WG (2w,0m,0d)",23.03.2024,475,23,Berlin Charlottenburg,01.04.2024,
14,10369293,wg-zimmer-in-Berlin-Prenzlauer-Berg.10369293.html,"2er WG (0w,0m,0d)",23.03.2024,540,20,Berlin Prenzlauer Berg,23.03.2024,
15,10439757,wg-zimmer-in-Berlin-Wilmersdorf.10439757.html,"3er WG (1w,1m,0d)",23.03.2024,999,20,Berlin Wilmersdorf,01.04.2024,
16,10734456,wg-zimmer-in-Berlin-Weissensee.10734456.html,"3er WG (0w,0m,0d)",23.03.2024,690,12,Berlin Weißensee,01.04.2024,
17,6205391,wg-zimmer-in-Berlin-Pankow.6205391.html,"4er WG (1w,2m,0d)",23.03.2024,700,16,Berlin Pankow,01.07.2024,12.01.2027
18,10815305,wg-zimmer-in-Berlin-Friedenau.10815305.html,"3er WG (2w,0m,0d)",23.03.2024,850,16,Berlin Friedenau,01.08.2024,
19,10875671,wg-zimmer-in-Berlin-Kreuzberg.10875671.html,"4er WG (3w,0m,0d)",23.03.2024,382,19,Berlin Kreuzberg,15.03.2024,

### Connect to Google Spreadsheet

In [ ]:
# Authenticate and connect to Google Sheets
gc = gspread.service_account(filename="./service_account.json")

# Open the Google Sheets document
worksheet = gc.open("wg-gesucht_list").worksheet("list_data")

### Append data to Google Spreadsheet

In [ ]:
set_with_dataframe(worksheet, append_df, row=count_filled_rows(worksheet)+1, include_index=False, include_column_header=False)